databases:
  - name: jobportal-db
    plan: free
    databaseName: jobportal
    user: jobportal_user

services:
  - type: web
    name: job-portal
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn myproject.wsgi:application
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "false"
      - key: DATABASE_URL
        fromDatabase:
          name: jobportal-db
          property: connectionString
      - key: GEMINI_API_KEY
        generateValue: true
      - key: EMAIL_HOST_USER
        value: bkarthick.dev@gmail.com
      - key: EMAIL_HOST_PASSWORD
        value: ojizkuyxvpnkbgsd
